UEWeb/UEWeb/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UEWeb.Context;
using UEWeb.Models;
using PagedList;
using System.Threading.Tasks;

namespace UEWeb.Controllers
{
    public class CustomerController : Controller
    {
        private UEDbContext db = new UEDbContext();

      
        public async Task<ActionResult> Index(string search,int? page)
        {
            IQueryable<Customer> customers = null;
            ViewBag.CurrentSearch = search;
           
            if (string.IsNullOrWhiteSpace(search))
            {
                customers = db.Customers.OrderByDescending(o => o.Id).AsQueryable();
            }
            else
            {
                customers = db.Customers
                    .Where(c=>c.Name.Contains(search) || c.Address.Contains(search))
                    .OrderByDescending(o => o.Id)
                    .AsQueryable();
            }

            int pagesize = 10;
            int pageno = (page ?? 1);
            ViewBag.CurrentPage = pageno;
            return await Task.FromResult(View(customers.ToPagedList(pageno,pagesize)));
        }

         
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return await Task.FromResult( new  HttpStatusCodeResult(HttpStatusCode.BadRequest));
            }
            Customer customer = await db.Customers.Include(c =>   c.Invoices.Select(i=>i.InvoiceDetails)).FirstOrDefaultAsync(c=>c.Id==id);
            if (customer == null)
            {
                return await Task.FromResult(HttpNotFound());
            }
            customer.Invoices = customer.Invoices.Take(20).ToList();
            return  await Task.FromResult(View(customer));
        }

        
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Address,Contact")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                await db.SaveChangesAsync();
                return await Task.FromResult( RedirectToAction("Index"));
            }

            return await Task.FromResult(View(customer));
        }

       
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = await db.Customers.FindAsync(id);
            if (customer == null)
            {
                return await Task.FromResult( HttpNotFound());
            }
            return await Task.FromResult(View(customer));
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Address,Contact")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
               await db.SaveChangesAsync();
                return  RedirectToAction("Index");
            }
            return View(customer);
        }

        
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = await db.Customers.FindAsync(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Customer customer = await db.Customers.FindAsync(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UEWeb/UEWeb/Controllers/InvoiceController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using UEWeb.Context;
using UEWeb.Models;

namespace UEWeb.Controllers
{
    public class InvoiceController : Controller
    {
        private UEDbContext db = new UEDbContext();

         
        public async Task<ActionResult> Index(string search, int? page)
        {

            IQueryable<Invoice> invoices = null;
            ViewBag.CurrentSearch = search;

            if (string.IsNullOrWhiteSpace(search))
            {
                invoices = db.Invoices.Include(i => i.Customer).OrderByDescending(o => o.Id).AsQueryable();
            }
            else
            {
                invoices = db.Invoices.Include(i=>i.Customer)
                    .Where(c => c.Customer.Name.Contains(search) || (c.Id.ToString()+c.Date.Year.ToString()+c.InvoiceDetails.Count.ToString()).Contains(search))
                    .OrderByDescending(o => o.Id)
                    .AsQueryable();
            }

            int pagesize = 10;
            int pageno = (page ?? 1);
            ViewBag.CurrentPage = pageno;
            return await Task.FromResult(View(invoices.ToPagedList(pageno, pagesize)));
        }

        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Invoice invoice = db.Invoices
                                .Include(i => i.Customer)
                                .Include(i => i.InvoiceDetails.Select(p=>p.Product))                                
                                .Where(i => i.Id == id).FirstOrDefault(); 

            if (invoice == null)
            { 
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: Invoice/Create
        public ActionResult Create(int  customerId )
        {
            var customer = db.Customers.Find(customerId);
            return View(customer);
        }

         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date,CustomerId")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Invoices.Add(invoice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", invoice.CustomerId);
            return View(invoice);
        }

        
        public ActionResult Edit(int? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Invoice invoice = db.Invoices.Find(id);
            //if (invoice == null)
            //{
            //    return HttpNotFound();
            //}
            //ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", invoice.CustomerId);
            //return View(invoice);
            return Content("Invoice can not be edited.");
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,CustomerId")] Invoice invoice)
        {
            //if (ModelState.IsValid)
            //{
            //    db.Entry(invoice).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", invoice.CustomerId);
            //return View(invoice);

            return Content("Invoice can not be edited.");
        }

        // GET: Invoice/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices
                                .Include(i => i.Customer)
                                .Include(i => i.InvoiceDetails.Select(p => p.Product))
                                .Where(i => i.Id == id).FirstOrDefault();
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public async Task<ActionResult> Print(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Invoice invoice = db.Invoices
                                .Include(i => i.Customer)
                                .Include(i => i.InvoiceDetails.Select(p => p.Product))
                                .Where(i => i.Id == id).FirstOrDefault();

            if (invoice == null)
            {
                return HttpNotFound();
            }

            /// Pdf Section
            /// 

            Utilities.ViewRenderer viewRenderer = new Utilities.ViewRenderer(this.ControllerContext);

           string reportContent =  viewRenderer.RenderView($@"~/Views/Invoice/Print.cshtml", invoice);


            IronPdf.HtmlToPdf htmlToPdf = new IronPdf.HtmlToPdf();

            htmlToPdf.PrintOptions = new IronPdf.PdfPrintOptions()
            {
                PaperSize = IronPdf.PdfPrintOptions.PdfPaperSize.A4,
                PaperOrientation = IronPdf.PdfPrintOptions.PdfPaperOrientation.Portrait,
                MarginBottom = 0,
                MarginLeft = 0,
                MarginRight = 0,
                MarginTop = 0 
                
            };




            
            var waterMark = "<h1 style='font-size: 46px !important;' >Umair Enterprise</h1> <small>Developed By Muhammad Shakeel, Contact: 0346-9476404</small>";
            // var document = htmlToPdf.RenderUrlAsPdf($@"http://localhost:49767/Invoice/Details/{id}");
            var document = htmlToPdf.RenderHtmlAsPdf(reportContent);


           
            document.WatermarkAllPages( waterMark, IronPdf.PdfDocument.WaterMarkLocation.MiddleCenter, 20, -45);
          
            //return a  pdf document from a view
            var contentLength = document.BinaryData.Length;
            Response.AppendHeader("Content-Length", contentLength.ToString());
            Response.AppendHeader("Content-Disposition", "inline; filename=Invoice_" + id + ".pdf");
            return await Task.FromResult(File(document.BinaryData, "application/pdf;"));
        }

        public async Task<ActionResult> Test(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Invoice invoice = db.Invoices
                                .Include(i => i.Customer)
                                .Include(i => i.InvoiceDetails.Select(p => p.Product))
                                .Where(i => i.Id == id).FirstOrDefault();

            if (invoice == null)
            {
                return HttpNotFound();
            }

            return View("Print", invoice);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UEWeb/UEWeb/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UEWeb.Context;
using UEWeb.Models;
using PagedList;

namespace UEWeb.Controllers
{
    public class ProductController : Controller
    {
        private UEDbContext db = new UEDbContext();

        
        public ActionResult Index(string search,int? page)
        {
            IQueryable<Product> customers = null;
            ViewBag.CurrentSearch = search;

            if (string.IsNullOrWhiteSpace(search))
            {
                customers = db.Products.OrderByDescending(o => o.Id).AsQueryable();
            }
            else
            {
                customers = db.Products
                    .Where(c => c.Name.Contains(search) || c.Code.Contains(search))
                    .OrderByDescending(o => o.Id)
                    .AsQueryable();
            }

            int pagesize = 10;
            int pageno = (page ?? 1);
            ViewBag.CurrentPage = pageno;
            return View(customers.ToPagedList(pageno, pagesize));
        }

        // GET: Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Code,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Code,Price")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UEWeb/UEWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<br />
 
<div class="content">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<div class="card card-user">
				<div class="image">
					<img src="../assets/img//bg5.jpg" alt="...">
				</div>
				<div class="card-body">
					<div class="author">
						<a href="#">
							<img class="avatar border-gray" src="../assets/img//shakeel.jpg" alt="...">
							<h5 class="title">Muhammad Shakeel</h5>
						</a>
						<p class="description">
							Microsoft Certified Professional
						</p>
					</div>
					<p class="description text-center">
						Muhammad Shakeel is professional software developer. He developed many challenging applications including business solutions and ecommerce applications.
						<br />
						According to reasonable demand of software developement he accept only professional projects.
					</p>
				</div>
				 
			</div>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>

UEWeb/UEWeb/Views/Home/Contact.cshtml
@{
	ViewBag.Title = "Contact";
}

<style>
	.img{

		width:30px;
		height:30px;
	}
</style>

<br />

<div class="content">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<div class="card card-user">
				<div class="image">
					<img src="../assets/img//bg5.jpg" alt="...">
				</div>
				<div class="card-body">
					<div class="author">
						<a href="#">
							<img class="avatar border-gray" src="../assets/img//shakeel.jpg" alt="...">
							<h5 class="title">Muhammad Shakeel</h5>
						</a>
						<p class="description">
							Microsoft Certified Professional
						</p>
					</div>
					<p class="description text-center">
						<div class="row">
							<div class="col-md-12">
								<h5 class="text-muted"> 0346-947-6404</h5>
							</div>
							<hr>

							<div class="col-md-12">
								<h5 class="text-muted"> sshakeel404@@gmail.com</h5>
							</div>
							<hr>

							<div class="col-md-12">
								<h5 class="text-muted">sshakeel404@@hotmail.com</h5>
							</div>
							<hr>

						</div>
					</p>
				</div> 
			</div>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>

UEWeb/UEWeb/Views/Home/Index.cshtml
@model UEWeb.Models.Statistics 
<br />
<div class="content">
	<div class="row">
		<div class="col-lg-4">
			<div class="card card-chart">
				<div class="card-header">
					<h5 class="card-category">Top 5</h5>
					<h4 class="card-title text-primary">Customers</h4>
				</div>
				<div class="card-body">
					<div class="table-full-width table-responsive">
						<table class="table">
							<tbody>
								@foreach (var item in Model.Customers)
								{
									<tr>
										<td>
											<a class="text-info" href="@Url.Action("Details", "Customer", new { id = item.Id })">
											@item.Name <br />
												<small class="text-primary"><b>@item.Address</b> </small>
											</a>
										</td>

									</tr>
								}
								 
							</tbody>
						</table>
					</div> 
				</div>
				<div class="card-footer">
					<div class="stats">
						<i class="now-ui-icons arrows-1_refresh-69"></i> Just Updated
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="card card-chart">
				<div class="card-header">
					<h5 class="card-category">Top 5</h5>
					<h4 class="card-title text-primary">Invoices</h4>
				</div>
				<div class="card-body">
					<div class="table-full-width table-responsive">
						<table class="table">
							<tbody>
								@foreach (var item in Model.Invoices)
								{
									<tr>
										<td>
											<a class="text-info" href="@Url.Action("Details", "Invoice", new { id = item.Id })">
												@item.Customer.Name <br />
												<small class="text-primary">
													<b>@item.Id@item.Date.Year@item.InvoiceDetails.Count @@ @item.Date.ToLongDateString()</b>
												</small> 
											</a>
										</td>

									</tr>
								}
								 
							</tbody>
						</table>
					</div>
				</div>
				<div class="card-footer">
					<div class="stats">
						<i class="now-ui-icons arrows-1_refresh-69"></i> Just Updated
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="card card-chart">
				<div class="card-header">
					<h5 class="card-category">Top 5</h5>
					<h4 class="card-title text-primary">Products</h4>
				</div>
				<div class="card-body">
					<div class="table-full-width table-responsive">
						<table class="table">
							<tbody>
								@foreach (var item in Model.Products)
								{
								<tr>
									<td>
										<a class="text-info" href="@Url.Action("Details","Product",new {id=item.Id })">@item.Name <br />
										<small class="text-primary"><b> @item.Code</b></small>
										</a>
									</td>

								</tr>
								}
								 

							</tbody>
						</table>
					</div>
				</div>
				<div class="card-footer">
					<div class="stats">
						<i class="now-ui-icons arrows-1_refresh-69"></i> Just Updated
					</div>
				</div>
			</div>
		</div>

	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">
					 
					<h4 class="card-title">Recent Customer</h4>
				</div>
				<div class="card-body">
					<div class="table-full-width table-responsive">
						<table class="table">
							<tbody>
								@foreach (var item in Model.RecentCustomers)
								{
									<tr>
										<td>
											<a class="text-info" href="@Url.Action("Details", "Customer", new { id = item.Id })">
											@item.Name <br /> 
											<small class="text-primary"><b>@item.Address</b></small></a>
										</td>

									</tr>
								}
								  
							</tbody>
						</table>
					</div>
				</div>
				<div class="card-footer">
					<hr>
					<div class="stats">
						<i class="now-ui-icons loader_refresh"></i> Updated Now
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">
					<h5 class="card-category">All Persons List</h5>
					<h4 class="card-title"> Recent Invoices</h4>
				</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table">
							<thead class=" text-primary">
								<tr>
									<th>
										Customer Name
									</th>
									<th>
										Invoice
									</th>
									<th>
										 
									</th>
									 
								</tr>
							</thead>
							<tbody>

								@foreach (var item in Model.RecentInvoices)
								{
									<tr>
										<td>
											@item.Customer.Name
										</td>
										<td>
											@item.Id@item.Date.Year@item.InvoiceDetails.Count
										</td>
										<td>
											<a class="btn btn-success" href="@Url.Action("Details", "Invoice", new { id = item.Id })">
											 Details</a>

										</td>
										 
									</tr>
								}

							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>